services:
  - type: web
    name: abnormal-event-detection
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: STORAGE_PATH
        value: /var/data
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
